version: '3'

services:
  app:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    volumes:
      - .:/var/www/html
    expose:
      - 80
    ports:
      - "80:80"
    restart: unless-stopped
    command: php -d variables_order=EGPCS /var/www/html/artisan serve --host 0.0.0.0  --port 80
    networks:
      - default

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
